// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types manually

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          updated_at?: string
        }
      }
      devices: {
        Row: {
          id: string
          device_code: string
          user_id: string | null
          status: 'active' | 'inactive' | 'unlinked'
          linked_at: string | null
          unlinked_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          device_code: string
          user_id?: string | null
          status?: 'active' | 'inactive' | 'unlinked'
          linked_at?: string | null
          unlinked_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          device_code?: string
          user_id?: string | null
          status?: 'active' | 'inactive' | 'unlinked'
          linked_at?: string | null
          unlinked_at?: string | null
          created_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          user_id: string
          full_name: string | null
          photo_url: string | null
          birth_date: string | null
          phone: string | null
          address: string | null
          blood_type: string | null
          allergies: string[] | null
          medications: string[] | null
          medical_conditions: string[] | null
          custom_fields: Record<string, any> | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          full_name?: string | null
          photo_url?: string | null
          birth_date?: string | null
          phone?: string | null
          address?: string | null
          blood_type?: string | null
          allergies?: string[] | null
          medications?: string[] | null
          medical_conditions?: string[] | null
          custom_fields?: Record<string, any> | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          full_name?: string | null
          photo_url?: string | null
          birth_date?: string | null
          phone?: string | null
          address?: string | null
          blood_type?: string | null
          allergies?: string[] | null
          medications?: string[] | null
          medical_conditions?: string[] | null
          custom_fields?: Record<string, any> | null
          created_at?: string
          updated_at?: string
        }
      }
      emergency_contacts: {
        Row: {
          id: string
          user_id: string
          name: string
          relation: string
          phone: string
          email: string | null
          priority: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          relation: string
          phone: string
          email?: string | null
          priority?: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          relation?: string
          phone?: string
          email?: string | null
          priority?: number
          created_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          stripe_subscription_id: string | null
          status: 'active' | 'expired' | 'cancelled' | 'grace_period'
          start_date: string
          end_date: string
          auto_renew: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          stripe_subscription_id?: string | null
          status?: 'active' | 'expired' | 'cancelled' | 'grace_period'
          start_date: string
          end_date: string
          auto_renew?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          stripe_subscription_id?: string | null
          status?: 'active' | 'expired' | 'cancelled' | 'grace_period'
          start_date?: string
          end_date?: string
          auto_renew?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          name: string
          description: string | null
          price: number
          stripe_price_id: string | null
          stock: number
          images: string[] | null
          category: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          price: number
          stripe_price_id?: string | null
          stock?: number
          images?: string[] | null
          category?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          price?: number
          stripe_price_id?: string | null
          stock?: number
          images?: string[] | null
          category?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      access_logs: {
        Row: {
          id: string
          device_id: string
          accessed_at: string
          location: Record<string, any> | null
          ip_address: string | null
        }
        Insert: {
          id?: string
          device_id: string
          accessed_at?: string
          location?: Record<string, any> | null
          ip_address?: string | null
        }
        Update: {
          id?: string
          device_id?: string
          accessed_at?: string
          location?: Record<string, any> | null
          ip_address?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
